# Generated by Django 4.2.1 on 2023-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0004_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thongtintuyensinh",
            name="content",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
