# Generated by Django 4.2.1 on 2023-05-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0006_gioithieuvetruong_thongtintuyensinh_is_delete_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GioiThieuVeTruong",
            new_name="InforSchool",
        ),
    ]
