# Generated by Django 4.2.1 on 2023-05-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0007_rename_gioithieuvetruong_inforschool"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InforSchool",
            new_name="BannerSchool",
        ),
        migrations.RemoveField(
            model_name="thongtintuyensinh",
            name="comment_number",
        ),
    ]
