# Generated by Django 4.2.1 on 2023-05-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0008_rename_inforschool_bannerschool_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentOnInforSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("content", models.CharField(max_length=1000)),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InforSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=10000)),
                ("img", models.ImageField(null=True, upload_to="infoschoo/%y%m%d")),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
