# Generated by Django 4.2.1 on 2023-05-05 18:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0010_bannerschool_user_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyManagerOfSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=10000)),
                ("website", models.CharField(max_length=100)),
                ("video", models.CharField(max_length=100, null=True)),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StandardPointOfFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("content", models.CharField(max_length=1000)),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FacultyOfSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "operation_day",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 5, 6, 1, 57, 2, 624666)
                    ),
                ),
                (
                    "infor_faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuyensinh.facultymanagerofschool",
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="facultymanagerofschool",
            name="standard_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tuyensinh.standardpointoffaculty",
            ),
        ),
    ]
