# Generated by Django 4.2.1 on 2023-05-05 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0011_facultymanagerofschool_standardpointoffaculty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpointoffaculty",
            name="name_faculty",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="facultymanagerofschool",
            name="standard_point",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tuyensinh.standardpointoffaculty",
            ),
        ),
        migrations.AlterField(
            model_name="facultyofschool",
            name="infor_faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tuyensinh.facultymanagerofschool",
            ),
        ),
        migrations.AlterField(
            model_name="facultyofschool",
            name="operation_day",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 6, 2, 10, 42, 876495)
            ),
        ),
    ]
