# Generated by Django 4.2.1 on 2023-05-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0012_standardpointoffaculty_name_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyofschool",
            name="operation_day",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 6, 2, 13, 46, 79362)
            ),
        ),
        migrations.AlterField(
            model_name="standardpointoffaculty",
            name="name_faculty",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
