# Generated by Django 4.2.1 on 2023-05-08 13:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0013_alter_facultyofschool_operation_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inforschool",
            name="user_name",
        ),
        migrations.RemoveField(
            model_name="facultyofschool",
            name="infor_faculty",
        ),
        migrations.RemoveField(
            model_name="facultyofschool",
            name="name",
        ),
        migrations.RemoveField(
            model_name="facultyofschool",
            name="user_name",
        ),
        migrations.RemoveField(
            model_name="standardpointoffaculty",
            name="name_faculty",
        ),
        migrations.AddField(
            model_name="commentoninforschool",
            name="thongtintuyensinh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tuyensinh.thongtintuyensinh",
            ),
        ),
        migrations.AddField(
            model_name="facultyofschool",
            name="content",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="facultyofschool",
            name="name_faculty",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facultyofschool",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facultyofschool",
            name="video",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facultyofschool",
            name="website",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="standardpointoffaculty",
            name="facultyofschool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tuyensinh.facultyofschool",
            ),
        ),
        migrations.AddField(
            model_name="standardpointoffaculty",
            name="year",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="bannerschool",
            name="img_banner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="facultyofschool",
            name="operation_day",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 8, 20, 30, 14, 997487)
            ),
        ),
        migrations.AlterField(
            model_name="thongtintuyensinh",
            name="image",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="FacultyManagerOfSchool",
        ),
        migrations.DeleteModel(
            name="InforSchool",
        ),
    ]
