# Generated by Django 4.2.1 on 2023-05-08 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0014_remove_inforschool_user_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bannerschool",
            old_name="user_name",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="commentoninforschool",
            old_name="user_name",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="facultyofschool",
            name="operation_day",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 8, 20, 47, 50, 907079)
            ),
        ),
    ]
