# Generated by Django 4.2.1 on 2023-05-08 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0015_rename_user_name_bannerschool_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentoninforschool",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="facultyofschool",
            name="operation_day",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 8, 20, 51, 22, 951696)
            ),
        ),
    ]
