# Generated by Django 4.2.1 on 2023-05-08 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0016_alter_commentoninforschool_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentoninforschool",
            name="thongtintuyensinh",
        ),
        migrations.AlterField(
            model_name="facultyofschool",
            name="operation_day",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 8, 21, 36, 33, 811289)
            ),
        ),
    ]
