# Generated by Django 4.2.1 on 2023-05-08 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0017_remove_commentoninforschool_thongtintuyensinh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentoninforschool",
            name="thongtintuyensinh",
            field=models.ManyToManyField(
                blank=True, null=True, to="tuyensinh.thongtintuyensinh"
            ),
        ),
        migrations.AlterField(
            model_name="facultyofschool",
            name="operation_day",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 8, 21, 39, 2, 460036)
            ),
        ),
    ]
