# Generated by Django 4.2.1 on 2023-05-08 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0019_alter_facultyofschool_operation_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentoninforschool",
            name="thongtintuyensinh",
        ),
        migrations.AlterField(
            model_name="facultyofschool",
            name="operation_day",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 8, 21, 50, 16, 663711)
            ),
        ),
        migrations.RemoveField(
            model_name="thongtintuyensinh",
            name="loaithongtintuyensinh",
        ),
        migrations.AddField(
            model_name="commentoninforschool",
            name="thongtintuyensinh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tuyensinh.thongtintuyensinh",
            ),
        ),
        migrations.AddField(
            model_name="thongtintuyensinh",
            name="loaithongtintuyensinh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tuyensinh.loaithongtintuyensinh",
            ),
        ),
    ]
