# Generated by Django 4.2.1 on 2023-05-08 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuyensinh", "0020_remove_commentoninforschool_thongtintuyensinh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyofschool",
            name="operation_day",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 8, 21, 54, 6, 522438)
            ),
        ),
        migrations.RemoveField(
            model_name="thongtintuyensinh",
            name="loaithongtintuyensinh",
        ),
        migrations.AddField(
            model_name="thongtintuyensinh",
            name="loaithongtintuyensinh",
            field=models.ManyToManyField(
                blank=True, null=True, to="tuyensinh.loaithongtintuyensinh"
            ),
        ),
    ]
