# Generated by Django 4.2 on 2023-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtintuyensinh',
            name='image',
            field=models.ImageField(null=True, upload_to='thongtintuyensinhs/%Y/%m'),
        ),
    ]
