# Generated by Django 4.2 on 2023-04-26 20:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0002_thongtintuyensinh_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtintuyensinh',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
